### ISSUE TITLE
Dedaub2-A2: Stale checks from previous versions

### ISSUE THREAD

**Issue by danielattilasimon** [liquity/V2-gov#118]
In the `Governance::_allocateLQTY()` function, the length checks over the provided arrays have already been performed by the top-level `allocateLQTY()` function. As a result, they can be removed from the internal function since they are also incomplete after the introduction of the offsets as the offset arrays are not checked to have the same length as the rest arrays.

**Comment by bingen** [comment]
Just a note about the description of the issue: `_allocateLQTY` is also called from `_resetInitiatives`, but it has the proper lengths too.
